name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to DockerHub
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: hansemro/gdclip-docker:latest

  test-build:
    runs-on: ubuntu-latest
    needs: docker

    steps:
    - uses: actions/checkout@v3

    - name: Clone GDClip with submodules
      uses: actions/checkout@v3
      with:
        repository: hansemro/GDClip
        ref: build_test
        submodules: recursive
        path: GDClip

    - name: Apply patches to GDClip/godot-cpp
      run: cd GDClip/godot-cpp && git apply ../../*.patch

    - name: Pull the Docker image
      run: docker pull hansemro/gdclip-docker:latest

    - name: Get gcc version
      run: docker run --rm -t hansemro/gdclip-docker bash -c "gcc --version"

    - name: Get o64-clang version
      run: docker run --rm -t hansemro/gdclip-docker bash -c "o64-clang --version"

    - name: Get mingw-w64-gcc version
      run: docker run --rm -t hansemro/gdclip-docker bash -c "x86_64-w64-mingw32-gcc --version"

    - name: Build for Linux
      run: >-
        docker run --rm -t
        -u $(id -u $USER):$(id -g $USER)
        -v "${{ github.workspace }}":"/github/workspace"
        hansemro/gdclip-docker
        bash -c "cd /github/workspace/GDClip && make PLATFORM=linux NPROC=$(nproc)"

    - name: Build for macOS
      run: >-
        docker run --rm -t
        -u $(id -u $USER):$(id -g $USER)
        -v "${{ github.workspace }}":"/github/workspace"
        --env CXX=o64-clang++
        hansemro/gdclip-docker
        bash -c "cd /github/workspace/GDClip && make PLATFORM=osx NPROC=$(nproc)"

    - name: Build for Windows
      run: >-
        docker run --rm -t
        -u $(id -u $USER):$(id -g $USER)
        -v "${{ github.workspace }}":"/github/workspace"
        --env CXX=x86_64-w64-mingw32-g++
        hansemro/gdclip-docker
        bash -c "cd /github/workspace/GDClip && make PLATFORM=windows NPROC=$(nproc)"

    - name: Upload built library artifacts
      uses: actions/upload-artifact@v3
      with:
        path: ${{ github.workspace }}/GDClip/bin/*
        retention-days: 10
